### ISSUE TITLE
trezor hardware was not identifying

### ISSUE THREAD

**Issue by AndrewIammatteo** [BitcoinCacheMachine/BitcoinCacheMachine#28]
```
andy@spectre:~/git/github/bcm$ bcm init
Restarted.
GNUPGHOME: /home/andy/.bcm/gnupg
Your Trezor-backed GPG certificates do not exist. Let's create them now. Make sure you have your Trezor handy.
Please enter the title of the certificate. This is usually your name:  
Certificate Title:  Andrew Iammatteo
Please enter the username of the certificate. This is the username part of an email address:  
Username:  andy
Please enter the domain name of the certificate. This is the FQDN/domain of the email address:  
Domain Name:  bcm
Your certificate will appear as:  'Andrew Iammatteo andy@bcm'
DISPLAY not defined
2019-04-10 22:12:19,933 WARNING      This GPG tool is still in EXPERIMENTAL mode, so please note that the API and features may change without backwards compatibility! [__init__.py:118]
2019-04-10 22:12:19,946 WARNING      NOTE: in order to re-generate the exact same GPG key later, run this command with "--time=1554934339" commandline flag (to set the timestamp of the GPG key manually). [__init__.py:35]
2019-04-10 22:12:20,158 ERROR        Failed to enumerate WebUsbTransport. USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]                        [__init__.py:124]
Traceback (most recent call last):
  File "/usr/local/bin/trezor-gpg", line 11, in <module>
    load_entry_point('trezor-agent', 'console_scripts', 'trezor-gpg')()
  File "/tmp/trezor/agents/trezor/trezor_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/usr/local/lib/python3.6/dist-packages/libagent/gpg/__init__.py", line 324, in main
    return args.func(device_type=device_type, args=args)
  File "/usr/local/lib/python3.6/dist-packages/libagent/gpg/__init__.py", line 182, in run_init
    export_public_key(device_type, args))
  File "/usr/local/lib/python3.6/dist-packages/libagent/gpg/__init__.py", line 39, in export_public_key
    verifying_key = c.pubkey(identity=identity, ecdh=False)
  File "/usr/local/lib/python3.6/dist-packages/libagent/gpg/client.py", line 27, in pubkey
    with self.device:
  File "/usr/local/lib/python3.6/dist-packages/libagent/device/interface.py", line 126, in __enter__
    self.conn = self.connect()
  File "/usr/local/lib/python3.6/dist-packages/libagent/device/trezor.py", line 51, in connect
    raise interface.NotFoundError('{} not connected'.format(self))
libagent.device.interface.NotFoundError: Trezor not connected
```

**Comment by AndrewIammatteo** [comment]
This issue was at the first time using bcm after reformatting. Seemed to be resolved when bridge was installed. Try to resolve the issue. If trezor-bridge is a dependency it needs to be added to the list of dependencies.

**Comment by farscapian** [comment]
Closed due to age.
